#!/usr/bin/env bash
# Linux + CUDA training wrapper — Unsloth bf16 LoRA path.
#
# Unsloth's reference Qwen3.5 LoRA notebooks already implement R-Tuning
# SFT and ORPO; rewriting them in-tree just adds maintenance burden
# without improving correctness. This wrapper:
#
#   1. Validates the environment (CUDA visible, bf16 supported)
#   2. Generates a python entrypoint that loads hyperparameters from
#      hyperparams.yaml, builds the Unsloth model + dataset, and runs
#      `trl.SFTTrainer` (stage 1) or `trl.ORPOTrainer` (stage 2).
#   3. Hands off to that entrypoint.
#
# The generated entrypoint is intentionally minimal — change it once
# Unsloth publishes a new recipe; don't fork it. Build-plan reference:
# RTX 4090 24GB fits 9B bf16 LoRA at ~22 GB used.
#
# Prereqs:
#   pip install -U "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
#   pip install -U trl peft accelerate datasets pyyaml
#
# Usage:
#   ./train_unsloth.sh sft   path/to/sft.jsonl
#   ./train_unsloth.sh orpo  path/to/orpo.jsonl   adapters/sft
set -euo pipefail

cd "$(dirname "$0")"

stage="${1:-}"
data_file="${2:-}"
base_adapter="${3:-}"

if [ -z "$stage" ] || [ -z "$data_file" ]; then
  echo "Usage: $0 {sft|orpo} <data.jsonl> [base_adapter_dir]"
  exit 1
fi

if ! command -v nvidia-smi >/dev/null; then
  echo "ERROR: nvidia-smi not found. Did you mean train_mlx.sh?"
  exit 1
fi

entry=$(mktemp -t unsloth-train.XXXXXX.py)
trap 'rm -f "$entry"' EXIT

cat >"$entry" <<'PY'
"""Auto-generated by train_unsloth.sh — do not edit in place."""
import json, os, sys, yaml
from pathlib import Path

stage = sys.argv[1]
data_file = sys.argv[2]
base_adapter = sys.argv[3] if len(sys.argv) > 3 else None

cfg = yaml.safe_load(open("hyperparams.yaml"))
section = cfg[stage]

from unsloth import FastLanguageModel
model_name = section.get("base_model") or cfg["sft"]["base_model"]
max_seq_length = section["batch"]["max_seq_length"]
print(f"[unsloth] Loading {model_name} (max_seq={max_seq_length})")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=model_name,
    max_seq_length=max_seq_length,
    dtype=None,           # auto bf16 on Ampere+ ; build plan: NEVER 4-bit
    load_in_4bit=False,
)
lora = section.get("lora", cfg["sft"]["lora"])
model = FastLanguageModel.get_peft_model(
    model,
    r=lora["r"],
    lora_alpha=lora["lora_alpha"],
    lora_dropout=lora["lora_dropout"],
    target_modules=lora["target_modules"],
    use_gradient_checkpointing=lora["use_gradient_checkpointing"],
    random_state=lora["random_state"],
)
if base_adapter:
    print(f"[unsloth] Resuming from {base_adapter}")
    model.load_adapter(base_adapter)

# Load the dataset — JSONL of {messages: [{role, content}, ...]} for
# SFT, or {prompt, chosen, rejected} for ORPO.
from datasets import load_dataset
ds = load_dataset("json", data_files=data_file, split="train")

opt = section["optim"]
batch = section["batch"]
common_args = dict(
    learning_rate=opt["learning_rate"],
    num_train_epochs=opt["num_train_epochs"],
    warmup_ratio=opt["warmup_ratio"],
    lr_scheduler_type=opt["lr_scheduler_type"],
    optim=opt["optimizer"],
    bf16=opt["bf16"],
    per_device_train_batch_size=batch["per_device_train_batch_size"],
    gradient_accumulation_steps=batch["gradient_accumulation_steps"],
    output_dir=section["adapter_dir"],
    save_strategy="no",
    logging_steps=10,
    report_to="none",
)

if stage == "sft":
    from trl import SFTTrainer
    from transformers import TrainingArguments
    trainer = SFTTrainer(
        model=model,
        train_dataset=ds,
        tokenizer=tokenizer,
        args=TrainingArguments(**common_args),
        max_seq_length=max_seq_length,
        dataset_text_field=None,    # uses messages format
    )
elif stage == "orpo":
    from trl import ORPOTrainer, ORPOConfig
    args = ORPOConfig(beta=section["beta"], **common_args)
    trainer = ORPOTrainer(model=model, train_dataset=ds, tokenizer=tokenizer, args=args)
else:
    raise SystemExit(f"Unknown stage: {stage}")

print(f"[unsloth] Training stage={stage} → {section['adapter_dir']}")
trainer.train()
model.save_pretrained(section["adapter_dir"])
tokenizer.save_pretrained(section["adapter_dir"])
print(f"[unsloth] Saved adapter → {section['adapter_dir']}")
PY

python3 "$entry" "$stage" "$data_file" ${base_adapter:+"$base_adapter"}
